var fonts = {
	NotoSansRTL: {
		normal: "examples/fonts/NotoSansRTL-Regular.ttf",
		bold: "examples/fonts/NotoSansRTL-Bold.ttf",
		italics: "examples/fonts/NotoSansRTL-Regular.ttf",
		bolditalics: "examples/fonts/NotoSansRTL-Bold.ttf",
	},
	Roboto: {
		normal: "examples/fonts/Roboto-Regular.ttf",
		bold: "examples/fonts/Roboto-Medium.ttf",
		italics: "examples/fonts/Roboto-Italic.ttf",
		bolditalics: "examples/fonts/Roboto-MediumItalic.ttf",
	},
};

var PdfPrinter = require("../src/printer");
var printer = new PdfPrinter(fonts);
var fs = require("fs");

// for ease of assigning fonts
const hebrew = "NotoSansRTL";
const english = "Roboto";

const shortEnglish = "The man and his dog";
const mediumEnglish = "The man and his dog and his cat";
const longEnglish =
	"The man and his dog and his cat and his snake went for a really long walk to ensure that they started a new line";
const superLongEnglish =
	"The man and his dog and his cat and his snake went for a really long walk to ensure that they started a new line but the problem was that this wasn't necessarily a new line in hebrew";
const longEnglishWithPunctuation =
	"The man, [his] dog: his cat! and his (snake) went {} for a really <long> walk to /ensure? that ...they started a new line";
const longEnglishWithNewlines =
	"The man and his dog and his cat\nand his snake went for a really long walk\nto test out newlines";
// All hebrew sentences generated by using google translate on the corresponding english sentences
// A space is then manually added to the RHS of the string - required for current way that BIDI is
// implemented to avoid word order problems

const shortHebrew = "האיש וכלבו ";
const mediumHebrew = "האיש וכלבו והחתול שלו ";
const longHebrew =
	"האיש וכלבו והחתול שלו והנחש שלו יצאו לטיול ממש ארוך כדי להבטיח שהם מתחילים קו חדש ";
const superLongHebrew =
	"האיש וכלבו והחתול שלו והנחש שלו יצאו לטיול ממש ארוך כדי להבטיח שהם מתחילים קו חדש אבל הבעיה הייתה שזה לא בהכרח קו חדש בעברית ";
const longHebrewWithPunctuation =
	"האיש, הכלב שלו: החתול שלו! שלו (הנחש) הלך {} להליכה ממש <ארוכה> כדי / להבטיח? ש ... הם התחילו קו חדש ";
const longHebrewWithNewlines =
	"האיש וכלבו והחתול שלו \nוהנחש שלו הלך לטייל ממש ארוך \nכדי לבדוק קווים חדשים ";

let testCounter = 0;
const generateTestHeader = (string) => {
	return { text: string, fontSize: 16 };
};
const generateTestString = (string) => {
	return { text: `Test ${testCounter++}: ${string}` };
};

// accepts an array of arrays [string, language]
const generateInlineRtlTest = (stringsAndLanguages = []) => {
	const nestedTextArray = [];
	stringsAndLanguages.forEach(([string, language], i) => {
		let displayString = string;
		// from the UI we're expecting to get space separated chunks of
		// inline text, so this adds a space to all strings apart from first and
		// last
		if (i !== stringsAndLanguages.length - 1) {
			displayString += " ";
		}
		nestedTextArray.push({
			text: displayString,
			font: language,
			inlineRtl: language === hebrew,
		});
	});
	return {
		text: nestedTextArray,
	};
};
const generateRtlTest = (string, font = "Roboto") => {
	return { text: string, font, rtl: font === hebrew };
};
const newline = () => {
	return { text: "\n" };
};

const HEBREW_TESTS = [
	generateTestString("Short line"),
	generateInlineRtlTest([[shortHebrew, hebrew]]),
	generateRtlTest(shortHebrew, hebrew),
	newline(),
	generateTestString("Medium line"),
	generateInlineRtlTest([[mediumHebrew, hebrew]]),
	generateRtlTest(mediumHebrew, hebrew),
	newline(),
	generateTestString("Long line"),
	generateInlineRtlTest([[longHebrew, hebrew]]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
	generateTestString("Super long line"),
	generateInlineRtlTest([[superLongHebrew, hebrew]]),
	generateRtlTest(superLongHebrew, hebrew),
	newline(),
	generateTestString("Long line plus punctuation"),
	generateInlineRtlTest([[longHebrewWithPunctuation, hebrew]]),
	generateRtlTest(longHebrewWithPunctuation, hebrew),
	newline(),
	generateTestString("Long line with newline characters"),
	generateInlineRtlTest([[longHebrewWithNewlines, hebrew]]),
	generateRtlTest(longHebrewWithNewlines, hebrew),
	newline(),
];

const ENGLISH_HEBREW_TESTS = [
	generateTestString("Short"),
	generateInlineRtlTest([
		[shortEnglish, english],
		[shortHebrew, hebrew],
	]),
	generateRtlTest(shortHebrew, hebrew),
	newline(),
	generateTestString("Medium"),
	generateInlineRtlTest([
		[mediumEnglish, english],
		[mediumHebrew, hebrew],
	]),
	generateRtlTest(mediumHebrew, hebrew),
	newline(),
	generateTestString("Long (english line-break)"),
	generateInlineRtlTest([
		[longEnglish, english],
		[longHebrew, hebrew],
	]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
	generateTestString("Medium-long (hebrew line-break)"),
	generateInlineRtlTest([
		[mediumEnglish, english],
		[longHebrew, hebrew],
	]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
	generateTestString("Medium-long 2 (hebrew line-break)"),
	generateInlineRtlTest([
		[mediumEnglish + " some nonsense for spacing", english],
		[longHebrew, hebrew],
	]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
];

const HEBREW_ENGLISH_TESTS = [
	generateTestString("Short"),
	generateInlineRtlTest([
		[shortHebrew, hebrew],
		[shortEnglish, english],
	]),
	generateRtlTest(shortHebrew, hebrew),
	newline(),
	generateTestString("Medium"),
	generateInlineRtlTest([
		[mediumHebrew, hebrew],
		[mediumEnglish, english],
	]),
	generateRtlTest(mediumHebrew, hebrew),
	newline(),
	generateTestString("Long (english line-break)"),
	generateInlineRtlTest([
		[longHebrew, hebrew],
		[longEnglish, english],
	]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
	generateTestString(
		"Double long (hebrew line-break), nb this entire first line reads right to left"
	),
	generateInlineRtlTest([
		[longHebrew, hebrew],
		[longHebrew, hebrew],
		[mediumEnglish, english],
	]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
];

const ENGLISH_HEBREW_ENGLISH_TESTS = [
	generateTestString("Short"),
	generateInlineRtlTest([
		[shortEnglish, english],
		[shortHebrew, hebrew],
		[shortEnglish, english],
	]),
	generateRtlTest(shortHebrew, hebrew),
	newline(),
	generateTestString("Medium"),
	generateInlineRtlTest([
		[mediumEnglish, english],
		[mediumHebrew, hebrew],
		[mediumEnglish, english],
	]),
	generateRtlTest(mediumHebrew, hebrew),
	newline(),
	generateTestString("Long (english line-break)"),
	generateInlineRtlTest([
		[longEnglish, english],
		[longHebrew, hebrew],
		[longEnglish, english],
	]),
	generateRtlTest(longHebrew, hebrew),
	generateTestString("Long (hebrew line-break)"),
	generateInlineRtlTest([
		[longEnglish + " some more words to generate a hebrew line break", english],
		[longHebrew, hebrew],
		[longEnglish, english],
	]),
	generateRtlTest(longHebrew, hebrew),
];

const HEBREW_ENGLISH_HEBREW_TESTS = [
	generateTestString("Short"),
	generateInlineRtlTest([
		[shortHebrew, hebrew],
		[shortEnglish, english],
		[shortHebrew, hebrew],
	]),
	generateRtlTest(shortHebrew, hebrew),
	newline(),
	generateTestString("Medium"),
	generateInlineRtlTest([
		[mediumHebrew, hebrew],
		[mediumEnglish, english],
		[mediumHebrew, hebrew],
	]),
	generateRtlTest(mediumHebrew, hebrew),
	newline(),
	generateTestString("Long (english line-break)"),
	generateInlineRtlTest([
		[longHebrew, hebrew],
		[longEnglish, english],
		[longHebrew, hebrew],
	]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
	generateTestString("Double long (hebrew line-break)"),
	generateInlineRtlTest([
		[longHebrew, hebrew],
		[mediumEnglish, english],
		[longHebrew, hebrew],
	]),
	generateRtlTest(longHebrew, hebrew),
	newline(),
];

const MIXED_TESTS = [
	generateTestString("mix of strings, hebrew order long, medium, short"),
	generateInlineRtlTest([
		[mediumEnglish, english],
		[longHebrew, hebrew],
		[shortEnglish, english],
		[mediumHebrew, hebrew],
		[mediumEnglish, english],
		[shortHebrew, hebrew],
	]),
	generateRtlTest(longHebrew, hebrew),
	generateRtlTest(mediumHebrew, hebrew),
	generateRtlTest(shortHebrew, hebrew),
];

var docDefinition = {
	content: [
		generateTestHeader(
			"HEBREW ONLY: inlineRtl (left justified) FOLLOWED BY rtl (right justified)"
		),
		...HEBREW_TESTS,
		generateTestHeader(
			"HEBREW-ENGLISH-MIX: inlineRtl FOLLOWED BY rtl (right justified) to allow checking of hebrew"
		),
		generateTestHeader("ENGLISH-HEBREW"),
		...ENGLISH_HEBREW_TESTS,
		generateTestHeader("HEBREW-ENGLISH"),
		...HEBREW_ENGLISH_TESTS,
		generateTestHeader("ENGLISH-HEBREW-ENGLISH"),
		...ENGLISH_HEBREW_ENGLISH_TESTS,
		generateTestHeader("HEBREW-ENGLISH-HEBREW"),
		...HEBREW_ENGLISH_HEBREW_TESTS,
		generateTestHeader("MIXED TESTS"),
		...MIXED_TESTS,
	],
};

var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream("examples/pdfs/hebrew-tests.pdf"));
pdfDoc.end();
